### ISSUE TITLE
예시) 2023/04/19 ~ 2023/04/25 12주차

### ISSUE THREAD

**Issue by madirony** [kimdozzi/2023-codingtest-study#17]
[2023/04/19 ~ 2023/04/25 12주차](https://www.acmicpc.net/group/practice/view/16598/12)
[BOJ]
- [카카오머니](https://www.acmicpc.net/problem/15998)
- [성냥개비](https://www.acmicpc.net/problem/3687)
- [상금 헌터](https://www.acmicpc.net/problem/15953)
- [랜선 자르기](https://www.acmicpc.net/problem/1654)
- [나무 자르기](https://www.acmicpc.net/problem/2805)

**Comment by kimdozzi** [comment]
V
